baseURL = "http://pancho.dev/"
languageCode = "en-us"
title = "pancho.dev"
#CanonifyURLs=true
theme = "ramium"
#disqusShortname = "disqus-code"
googleAnalytics = "UA-920705-12"
pluralizeListTitles = false
enableemoji = true

[params]
    description = "A description for the meta tag of the site"
#    googleSearch = "google-search-code"
    showDate = true # make false if dont want to show date for evergeen articles
    math = false # best to enable this in the front matter of a page
    githubLink = "rafed/ramium/"

    tagsInHome = 40     # set zero to not show in home page
    sectionsInHome = 5  # set zero to not show in home page
    paginatePostsPerPage = 5
    paginateTagsPerPage = 6

[taxonomies]
    tag = "tags"

[markup.goldmark.renderer]
    unsafe = true

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        weight = 2
            [[menu.main]]
                parent = "blog"
                name = "All Posts"
                url = "/posts/"
                weight = 3
